
var page=1;$(function(){banner();view();play();DY_scroll('.wgl_hide','.wgl_prev','.wgl_next','.wgl_scroll',3,false);$('.nav a').hover(function(){$(this).parent().next('li').find('a').addClass('bg_no');},function(){$('.nav a').removeClass('bg_no');$('.nav a.current').parent().next('li').find('a').addClass('bg_no');});$('.hot_g_tab a').mouseover(function(){if($(this).hasClass('current'))return false;else{$(this).addClass('on');}});$('.hot_g_tab a').mouseout(function(){$(this).removeClass('on');});$('.hot_g_tab a').click(function(){$('.hot_g_tab a').removeClass('current');$(this).addClass('current');var index=$(this).index();$("#hgl_tab").find('ul').hide();$("#hgl_tab").find('ul:eq('+index+')').fadeIn();});$('#alone_new li').hover(function(){$('#alone_new li').removeClass('ative');$(this).addClass('ative');});$('.wgl_scroll li:eq(0)').addClass('current');var curl=$('.wgl_scroll li.current').find('a').attr('data-url');var cgame=$('.wgl_scroll li.current').find('a').attr('data-game');$("#gurl").attr('href',curl);$("#stategame").attr('href',cgame);$('.wgl_scroll li').click(function(){$('.wgl_scroll li').removeClass('current');$(this).addClass('current');var index=$(this).attr('data-id');var url=$(this).find('a').attr('data-url');var game=$(this).find('a').attr('data-game');$("#gurl").attr('href',url);$("#stategame").attr('href',game);$("#webglwwrap,#webgameinfo").find('ul').hide();$("#webglwwrap,#webgameinfo").find('ul.'+index).show();});$(".hgl_list li:eq(0)").addClass('current');$('.hgll_box').find("div.syglbox:eq(0)").show();$('.hgl_list li').click(function(){$('.hgl_list li').removeClass('current');$(this).addClass('current');var index=$(this).index();$('.hgll_box').find("div.syglbox").hide();$('.hgll_box').find("div.syglbox:eq("+index+")").show();});$('.serlist_tab a').click(function(){$('.serlist_tab a').removeClass('current');$(this).addClass('current');page=1;kflist(page);});$('.hkan_btn').click(function(){clickview();})
$("#searbtn").click(function(){serbase();})
$('#hsl_dec tr.hsl_1').eq(0).addClass('hide');$('#hsl_dec tr.hsl_2').eq(0).addClass('ative');$('#hsl_dec tr.hsl_1').hover(function(){$('#hsl_dec').find('tr.ative').hide().prev('tr').show();$('#hsl_dec tr.hsl_2').hide();$('#hsl_dec').find('tr').removeClass('ative');$(this).hide();$(this).next('tr.hsl_2').addClass('ative').show();});var d=new Date().getDay();$('.week_menu a').removeClass('current');$('.week_menu a:eq('+d+')').addClass('current')
$(".week_con").find('ul').hide();$(".week_con").find('ul:eq('+d+')').show();$('.week_menu a').mouseenter(function(){$('.week_menu a').removeClass('current');$(this).addClass('current');var index=$(this).index();$(".week_con").find('ul').hide();$(".week_con").find('ul:eq('+index+')').show();});$('#imgtab a.tabpic').click(function(){$('#imgtab a.tabpic').removeClass('current');$(this).addClass('current');var index=$(this).index();$(".fun_img_con").find('ul').hide();$(".fun_img_con").find('ul:eq('+index+')').fadeIn();if(index==0){$(".fun_more").attr('href','http://news.65.com/pic/girl/');}
else{$(".fun_more").attr('href','http://news.65.com/pic/funny/');}});$('.hg_pc_btn a.hg_btntj').live('click',function(){api.gamepc(this);});$('.hg_pc_btn a').hover(function(){$(this).addClass('active');},function(){$(this).removeClass('active');});$(window).bind("scroll",function(){var top=$(this).scrollTop();if(top>=100){$(".lf_menu2,#mtop").fadeIn(100);}
else{$(".lf_menu2,#mtop").fadeOut(100);}});$('#gotop').click(function(){$('body,html').animate({scrollTop:0},400);return false;});$(".lf_menu a.m_btn").click(function(event){var index=$(this).attr('data-id');var id='#'+index;$("html,body").animate({scrollTop:$(id).offset().top},400);});var resetPos=function(){var width=$(window).width();var right=0;if(width>=1400){right=(width-1200)/2-50-$(".lf_menu").width();}else{right=0;}
$(".lf_menu").css({right:right});}
resetPos();$(window).resize(function(){resetPos();});var msie6=$.browser=='msie'&&$.browser.version<7;if(msie6){var menuYloc=$(".lf_menu").offset().top;$(window).scroll(function(){var offsetTop=menuYloc+$(window).scrollTop()+"px";$(".lf_menu").css({top:offsetTop});});$(window).scroll();};})
var serbase=function(){var url="http://news.65.com/search/";var word=$("#seatxt").val();if(location.href.indexOf("search")>=0){seaapi.ser(word);}
else{window.open(encodeURI(url+"?word="+word));}}
var banner=function(){var sWidth=$("#hn_banner").width();var banner_ul=$("#hn_banner ul");var b_len=$(banner_ul).find('li').length;var index=0;var btn='';for(var i=0;i<b_len;i++){btn+='<span class="ant_02"></span>';}
$("#hn_btn").append(btn);$("#hn_btn span").mouseenter(function(){index=$(this).index();showPics(index);}).eq(0).trigger("mouseenter");$(".hnbtn_tab").css("opacity",0.8).hover(function(){$(this).stop(true,false).animate({"opacity":"1"},300);},function(){$(this).stop(true,false).animate({"opacity":"0.8"},300);});$("#hn_btn_l").click(function(){index-=1;if(index==-1){index=b_len-1;}
showPics(index);});$("#hn_btn_r").click(function(){index+=1;if(index==b_len){index=0;}
showPics(index);});$(banner_ul).css("width",sWidth*(b_len));$(".hn_ban_box").hover(function(){clearInterval(picTimer);},function(){picTimer=setInterval(function(){showPics(index);index++
if(index===b_len){index=0};},3000);}).trigger("mouseleave");function showPics(index){var nowLeft=-index*sWidth;$(banner_ul).stop(true,false).animate({"left":nowLeft},{duration:500,easing:"easeInOutQuad"});$("#hn_btn span").stop(true,false).removeClass("on").eq(index).stop(true,false).addClass("on");}}
jQuery.easing['jswing']=jQuery.easing['swing'];jQuery.extend(jQuery.easing,{easeInOutQuad:function(x,t,b,c,d){if((t/=d/2)<1)return c/2*t*t+b;return-c/2*((--t)*(t-2)-1)+b;}});var play=function(){$("#play_atv").find("li:odd").addClass("even");var sheight=$("#play_atv ul li").height()*2;var banner_ul=$("#play_atv ul");var b_len=$(banner_ul).find('li').length;var index=0;var btn='';for(var i=0;i<b_len;i+=2){btn+='<i></i>';}
$(".tq_bt").append(btn);$(".tq_bt i").mouseenter(function(){index=$(this).index();showPics(index);}).eq(0).trigger("mouseenter");$(banner_ul).css("height",sheight*(b_len));function picTimer(){showPics(index);index++
if(index===b_len){index=0};};function showPics(index){var nowtop=-index*sheight;$(banner_ul).stop(true,false).animate({"top":nowtop},300);$(".tq_bt i").stop(true,false).removeClass("on").eq(index).stop(true,false).addClass("on");}}
var view=function(){$('.hkan_con li:gt(4)').hide();}
var current_num=1;var clickview=function(){var len=$('.hkan_con li').length;var current_page=5;var sum=Math.ceil(len/current_page);current_num+=1;if(current_num>sum){current_num=1;}
$.each($('.hkan_con li'),function(index,item){var start=current_page*(current_num-1);var end=current_page*current_num;if(index>=start&&index<end){$(this).fadeIn(200);}else{$(this).hide();}});}
function DY_scroll(wraper,prev,next,img,speed,or){var wraper=$(wraper);var prev=$(prev);var next=$(next);var img=$(img);var liimg=img.find('li').length;var w=img.find('li').outerWidth(true);var s=speed;next.click(function(){if(!img.is(":animated")&&liimg>1){img.animate({'margin-left':-w},function(){var index=img.find('li.current').index();img.find('li').eq(0).appendTo(img);img.css({'margin-left':0});img.find("li").removeClass('current');img.find("li:eq("+index+")").addClass('current');var index=$(".wgl_scroll li.current").attr('data-id');var url=$(".wgl_scroll li.current").find('a').attr('data-url');var game=$(".wgl_scroll li.current").find('a').attr('data-game');$("#gurl").attr('href',url);$("#stategame").attr('href',game);$("#webglwwrap,#webgameinfo").find('ul').hide();$("#webglwwrap,#webgameinfo").find('ul.'+index).show();});}});prev.click(function(){if(!img.is(":animated")&&liimg>1){var index=img.find('li.current').index();img.find('li:last').prependTo(img);img.css({'margin-left':-w});img.animate({'margin-left':0});img.find("li").removeClass('current');img.find("li:eq("+index+")").addClass('current');var index=$(".wgl_scroll li.current").attr('data-id');var url=$(".wgl_scroll li.current").find('a').attr('data-url');var game=$(".wgl_scroll li.current").find('a').attr('data-game');$("#gurl").attr('href',url);$("#stategame").attr('href',game);$("#webglwwrap,#webgameinfo").find('ul').hide();$("#webglwwrap,#webgameinfo").find('ul.'+index).show();}});if(or==true){ad=setInterval(function(){next.click();},s*1000);wraper.hover(function(){clearInterval(ad);},function(){ad=setInterval(function(){next.click();},s*1000);});};}